# Generated by Django 3.2.12 on 2022-07-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
