# Generated by Django 3.2.12 on 2022-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.CharField(max_length=255),
        ),
    ]
