# Generated by Django 3.2.12 on 2022-09-06 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0005_auto_20220906_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsiboUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isibo', to='schools.isibo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isibo_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'isibo_users',
                'ordering': ['created_at'],
            },
        ),
    ]
