# Generated by Django 3.2.12 on 2022-09-07 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0009_auto_20220907_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='isibo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isibo_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='isibousers',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isibo_student', to='schools.student'),
            preserve_default=False,
        ),
    ]
