# Generated by Django 3.2.12 on 2022-09-07 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0008_school_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isibousers',
            name='user',
        ),
    ]
