# Generated by Django 3.2.12 on 2022-09-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_student_isibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='district',
        ),
        migrations.RemoveField(
            model_name='school',
            name='province',
        ),
    ]
