# Generated by Django 3.2.12 on 2022-09-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20220907_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
