# Generated by Django 3.2.12 on 2022-09-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_auto_20220907_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='isibo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_isibo', to='schools.isibo'),
        ),
    ]
