# Generated by Django 3.2.12 on 2022-07-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
    ]
