# Generated by Django 3.2.12 on 2022-07-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table=None,
        ),
    ]
