# Generated by Django 3.2.12 on 2022-09-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='district',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='province',
        ),
    ]
