# Generated by Django 3.2.12 on 2022-09-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_student_isibo'),
        ('surveys', '0004_auto_20220907_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='isibo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_isibo', to='schools.isibo'),
        ),
        migrations.AddField(
            model_name='survey',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_school', to='schools.school'),
        ),
    ]
