# Generated by Django 3.2.12 on 2022-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20220907_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='parent_tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
