# Generated by Django 3.2.12 on 2022-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20220907_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
