# Generated by Django 3.2.12 on 2022-06-22 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('activities', '0002_alter_activity_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities_school', to='schools.school'),
            preserve_default=False,
        ),
    ]
