# Generated by Django 3.2.12 on 2022-06-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['create_at']},
        ),
    ]
