# Generated by Django 3.2.12 on 2022-09-07 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_teacher'),
        ('activities', '0004_alter_activity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities_school', to='schools.school'),
        ),
    ]
