# Generated by Django 3.2.12 on 2022-09-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_alter_student_isibo'),
        ('activities', '0006_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='isibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_isibo', to='schools.isibo'),
        ),
    ]
